### ISSUE TITLE
Kicked when placing signals next to powered rail

### ISSUE THREAD

**Issue by Betsumei** [MineMaarten/Signals#59]
I'm getting booted from my server when I place either block signals or path signals next to powered rail, or powered rail next to signals, and after that happens I have to restart the server to be able to reconnect.
![minecraft crash](https://user-images.githubusercontent.com/3742052/35405126-6e695660-01c2-11e8-9e0f-bcf60198fbdc.PNG)
latest.log doesn't show anything when this happens, other than
[12:55:42] [Server thread/INFO]: Betsumei lost connection: Disconnected
[12:55:42] [Server thread/INFO]: Betsumei left the game
[12:55:51] [Server thread/INFO]: There are 0/40 players online:

Here's my list of active mods:
![image](https://user-images.githubusercontent.com/3742052/35405279-dee7c7b4-01c2-11e8-98e0-84e5965a47dd.png)

**Comment by CplPibald** [comment]
I'm getting the same problem with a particular section of the track on my dedicated server.  The problem started when I placed a rail, but that piece of rail was removed, and now simply riding a cart in that area causes the error.  Once the error starts, any client gets continually booted that tries to load that chunk until I restart the server.

When this happens, I get a client log that looks like a runaway recursion.  There is no crash report.

```
[21:06:55] [Netty Client IO #20/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Tried to read NBT tag with too high complexity, depth > 512
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442) ~[ByteToMessageDecoder.class:4.1.9.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) ~[ByteToMessageDecoder.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [ByteToMessageDecoder.class:4.1.9.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [ByteToMessageDecoder.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [AbstractChannelHandlerContext.class:4.1.9.Final]
(about a dozen iterations of these same five lines)
Caused by: java.lang.RuntimeException: Tried to read NBT tag with too high complexity, depth > 512
	at net.minecraft.nbt.NBTTagList.func_152446_a(NBTTagList.java:44) ~[ge.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagList.func_152446_a(NBTTagList.java:63) ~[ge.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagList.func_152446_a(NBTTagList.java:63) ~[ge.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58) ~[fy.class:?]
(about 300 iterations of these three lines)
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:133) ~[gi.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:88) ~[gi.class:?]
	at net.minecraft.network.PacketBuffer.func_150793_b(PacketBuffer.java:315) ~[gy.class:?]
	at net.minecraft.network.play.server.SPacketUpdateTileEntity.func_148837_a(SourceFile:42) ~[ih.class:?]
```

The rail network on this server is thousands of blocks long, with block signals 500+ blocks apart.

This is a large custom modpack, but the only mods my pack has in common with @Betsumei are Signals, lostcities, Baubles, and Tinkers-Construct.

**Comment by MineMaarten** [comment]
Thanks for the reports. It looks like the problem is caused by Signals updating the client about how the rail network should be visualized. From what I can see purely the large rail section size is causing this. As a workaround, placing down more signals in between others might help with this, as that way, you have smaller rail sections.

I'm currently (the past week) been busy rewriting the mod behind the scenes, with the aim to not requiring the full rail network to be chunkloaded at all times to make the signaling/pathfinding work (just keeping the minecarts loaded, with a to be added 'ChunkLoader Cart' addon, should be enough).

From what I can see here this rewrite, as a side-effect, will fix this issue, as the Signals themselves won't keep track of the rail network anymore

I'm hoping to release this new version next week.

**Comment by MineMaarten** [comment]
A beta version of what I've explained above should be available shortly at https://minecraft.curseforge.com/projects/signals/files/2552172
