### ISSUE TITLE
Crash with Simply Loaders tank cart and the signal block

### ISSUE THREAD

**Issue by CrashHermit** [MineMaarten/Signals#86]
Greetings, I wasn't sure if I should report this issue to you or the Simply Loaders dev. When a tank cart crosses a signal block with a powered rail like in the picture below, this error is encountered. It only occurs when the tank cart reaches the powered rail and the signal block is activated, not just while on the track.

Also the cart engine could not be attached to the tank cart from Simply loaders.

![image](https://user-images.githubusercontent.com/7251126/46579120-1ad03280-c9d1-11e8-8bd5-455ea41d5137.png)

```---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (elulib-0.1.12.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.6-universal.jar)
  LoadingPlugin (Quark-r1.5-130.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.2-1.12.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.16.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 10/7/18 1:22 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.minemaarten.signals.rail.network.mc.MCTrain.pathfind(MCTrain.java:139)
	at com.minemaarten.signals.rail.network.mc.MCTrain.pathfind(MCTrain.java:131)
	at com.minemaarten.signals.rail.network.mc.MCTrain.pathfind(MCTrain.java:43)
	at com.minemaarten.signals.rail.network.NetworkState.pathfindTrains(NetworkState.java:314)
	at com.minemaarten.signals.rail.network.NetworkState.pathfindTrains(NetworkState.java:306)
	at com.minemaarten.signals.rail.network.NetworkState.update(NetworkState.java:70)
	at com.minemaarten.signals.rail.network.mc.MCNetworkState.update(MCNetworkState.java:203)
	at com.minemaarten.signals.rail.network.mc.RailNetworkManager.onPostServerTick(RailNetworkManager.java:282)
	at com.minemaarten.signals.event.EventHandler.onPostServerTick(EventHandler.java:169)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_655_EventHandler_onPostServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1051914808 bytes (1003 MB) / 2582118400 bytes (2462 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -Xmx6144m -Xms256m -XX:PermSize=256m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2760 61 mods loaded, 61 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                       | Version           | Source                                        | Signature                                |
	|:--------- |:------------------------ |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                | 1.12.2            | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp                      | 9.42              | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML                      | 8.0.99.99         | forge-1.12.2-14.23.4.2760.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                    | 14.23.4.2760      | forge-1.12.2-14.23.4.2760.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | foamfixcore              | 7.7.4             | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | elucore                  | 1.0               | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | codechickenlib           | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | ancientwarfare           | 1.12.2-2.6.1.390  | ancientwarfare-1.12.2-2.6.1.390.jar           | None                                     |
	| UCHIJAAAA | redstoneflux             | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | ancientwarfareautomation | 1.12.2-2.6.1.390  | ancientwarfare-1.12.2-2.6.1.390.jar           | None                                     |
	| UCHIJAAAA | ancientwarfarenpc        | 1.12.2-2.6.1.390  | ancientwarfare-1.12.2-2.6.1.390.jar           | None                                     |
	| UCHIJAAAA | ancientwarfarestructure  | @VERSION@         | ancientwarfare-1.12.2-2.6.1.390.jar           | None                                     |
	| UCHIJAAAA | ancientwarfarevehicle    | 1.12.2-2.6.1.390  | ancientwarfare-1.12.2-2.6.1.390.jar           | None                                     |
	| UCHIJAAAA | crafttweaker             | 4.1.10            | CraftTweaker2-1.12-4.1.10.jar                 | None                                     |
	| UCHIJAAAA | mtlib                    | 3.0.5             | MTLib-3.0.5.jar                               | None                                     |
	| UCHIJAAAA | modtweaker               | 4.0.13            | modtweaker-4.0.14.jar                         | None                                     |
	| UCHIJAAAA | jei                      | 4.12.1.217        | jei_1.12.2-4.12.1.217.jar                     | None                                     |
	| UCHIJAAAA | athenaeum                | 1.12.2-1.14.0     | athenaeum-1.12.2-1.14.0.jar                   | None                                     |
	| UCHIJAAAA | quark                    | r1.5-130          | Quark-r1.5-130.jar                            | None                                     |
	| UCHIJAAAA | autoreglib               | 1.3-20            | AutoRegLib-1.3-20.jar                         | None                                     |
	| UCHIJAAAA | baubles                  | 1.5.2             | Baubles-1.12-1.5.2.jar                        | None                                     |
	| UCHIJAAAA | betterfoliage            | 2.1.10            | BetterFoliage-MC1.12-2.1.10.jar               | None                                     |
	| UCHIJAAAA | blockcraftery            | 0.1.3             | blockcraftery-0.1.3.jar                       | None                                     |
	| UCHIJAAAA | buildinggadgets          | 1.6.2             | BuildingGadgets-1.6.2.jar                     | None                                     |
	| UCHIJAAAA | carryon                  | 1.11.1            | CarryOn MC1.12.2 v1.11.1.jar                  | None                                     |
	| UCHIJAAAA | chameleon                | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| UCHIJAAAA | ctm                      | MC1.12.2-0.3.2.18 | CTM-MC1.12.2-0.3.2.18.jar                     | None                                     |
	| UCHIJAAAA | chisel                   | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar                  | None                                     |
	| UCHIJAAAA | chiselsandbits           | 14.26             | chiselsandbits-14.26.jar                      | None                                     |
	| UCHIJAAAA | cofhcore                 | 4.6.1             | CoFHCore-1.12.2-4.6.1.22-universal.jar        | None                                     |
	| UCHIJAAAA | cookiecore               | 2.0.0             | cookiecore-1.12-2.0.0.jar                     | 4bbb70ebe391f24f7704e343108a9b21b44c1b10 |
	| UCHIJAAAA | ctgui                    | 1.0.0             | CraftTweaker2-1.12-4.1.10.jar                 | None                                     |
	| UCHIJAAAA | crafttweakerjei          | 2.0.2             | CraftTweaker2-1.12-4.1.10.jar                 | None                                     |
	| UCHIJAAAA | dsurround                | 3.4.9.16          | DynamicSurroundings-1.12.2-3.4.9.16.jar       | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHIJAAAA | presets                  | 3.4.9.16          | DynamicSurroundings-1.12.2-3.4.9.16.jar       | None                                     |
	| UCHIJAAAA | dynamictrees             | 1.12.2-0.8.2      | DynamicTrees-1.12.2-0.8.2.jar                 | None                                     |
	| UCHIJAAAA | thaumcraft               | 6.1.BETA25        | Thaumcraft-1.12.2-6.1.BETA25.jar              | None                                     |
	| UCHIJAAAA | dynamictreestc           | 1.12.2-1.1.2      | DynamicTreesTC-1.12.2-1.1.2.jar               | None                                     |
	| UCHIJAAAA | entityspring             | 2.0.1             | entityspring-2.0.1.jar                        | None                                     |
	| UCHIJAAAA | extrabitmanipulation     | 1.12.2-3.3.1      | ExtraBitManipulation-1.12.2-3.3.1.jar         | None                                     |
	| UCHIJAAAA | foamfix                  | 0.10.2-1.12.2     | foamfix-0.10.2-1.12.2.jar                     | None                                     |
	| UCHIJAAAA | waila                    | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| UCHIJAAAA | icarus                   | 1.0               | icarus-1.0.jar                                | None                                     |
	| UCHIJAAAA | journeymap               | 1.12.2-5.5.2      | journeymap-1.12.2-5.5.2.jar                   | None                                     |
	| UCHIJAAAA | magicfeather             | @VERSION@         | magicfeather-1.12.1-2.1.0.jar                 | None                                     |
	| UCHIJAAAA | millenaire               | Millénaire 6.2.10 | millenaire-1.12.2-6.2.10.jar                  | None                                     |
	| UCHIJAAAA | quickleafdecay           | 1.2.4             | QuickLeafDecay-MC1.12.1-1.2.4.jar             | None                                     |
	| UCHIJAAAA | sereneseasons            | 1.2.6             | SereneSeasons-1.12.2-1.2.6-universal.jar      | None                                     |
	| UCHIJAAAA | signals                  | 1.3.12-23         | Signals-1.12.2-1.3.12-23-universal.jar        | None                                     |
	| UCHIJAAAA | storagenetwork           | 1.12.2-1.2.9      | SimpleStorageNetwork-1.12.2-1.2.9.jar         | None                                     |
	| UCHIJAAAA | simplyloaders            | 1.0.0             | Simplyloaders-2.0.jar                         | None                                     |
	| UCHIJAAAA | stg                      | 1.12.2-1.2.3      | stg-1.12.2-1.2.3.jar                          | None                                     |
	| UCHIJAAAA | storagedrawers           | 1.12-5.3.5        | StorageDrawers-1.12.2-5.3.7.jar               | None                                     |
	| UCHIJAAAA | thaumicjei               | 1.2.1             | ThaumicJEI-1.12.2-1.5.3-20.jar                | None                                     |
	| UCHIJAAAA | thaumicperiphery         | 0.3.0             | thaumicperiphery-0.3.0.jar                    | None                                     |
	| UCHIJAAAA | toughasnails             | 3.1.0.115         | ToughAsNails-1.12.2-3.1.0.115-universal.jar   | None                                     |
	| UCHIJAAAA | vanillatools             | 1.1.0             | VanillaTools-1.12.2-1.1.0.2-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | wailaharvestability      | 1.1.12            | WailaHarvestability-mc1.12-1.1.12.jar         | None                                     |
	| UCHIJAAAA | xtones                   | 1.12-1.0.8-11     | Xtones-1.12-1.0.8-11.jar                      | None                                     |
	| UCHIJAAAA | dropt                    | 1.12.2-1.10.1     | dropt-1.12.2-1.10.1.jar                       | None                                     |
	| UCHIJAAAA | elulib                   | 0.1.12            | elulib-0.1.12.jar                             | None                                     |

	Loaded coremods (and transformers): 
FMLPlugin (elulib-0.1.12.jar)
  elucent.elulib.asm.ASMTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.6-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
LoadingPlugin (Quark-r1.5-130.jar)
  vazkii.quark.base.asm.ClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.2-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.16.jar)
  org.blockartistry.DynSurround.asm.Transformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'```

**Comment by MineMaarten** [comment]
This is a problem with Simply Loaders, I have created a pull request to resolve it on that side. https://github.com/theredghostwolf/SimplyLoaders-V2/pull/2
